__author__ = 'jph'

import datetime as dt
import random

from lib.events import FillEvent


class TradingHandler(object):
    """
    Handles interface between orders, generated by a portfolio and fills
    uses connection to brokerage
    """

    def __init__(self, queue):
        self.queue = queue

    def execute_order(self, event):
        """
        executes order
        """
        raise NotImplementedError


class FakeInstantTradingHandler(TradingHandler):
    """
    simulates instant fills
    """

    def __init__(self, queue):
        super(FakeInstantTradingHandler, self).__init__(queue=queue)
        self.fakeid = 37


    def execute_order(self, event):
        if event.type == 'ORDER':
            price = 190 + round(random.random() * 10, 2)
            fill_event = FillEvent(dt.datetime.today(), event.symbol,
                                   'BATS', event.quantity, event.side, 2, self.fakeid, price)
            self.fakeid += 1
            self.queue.put(fill_event)
